# Set the base image to Python
From ubuntu:latest
# File Author / Maintainer
MAINTAINER -Joe

RUN apt-get update
RUN apt-get install -y python3 python3-pip nginx
RUN pip3 install uwsgi

RUN pip install git pull https://github.com/Joegofett/family_wiki.git

RUN pip3 install -r requirements.txt
